services:
  mysql:
    image: mysql:8.0
    container_name: kioske_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: main
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: kioske
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 3

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "8081:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: